### ISSUE TITLE
install fails if `rsync` packages is being held

### ISSUE THREAD

**Issue by marcusboden** [przemeklal/charm-local-juju-users#10]
I encountered the following issue during the install hook:
```
unit-local-juju-users-3: 12:58:05 WARNING unit.local-juju-users/3.install E: Held packages were changed and -y was used without --allow-change-held-packages.
unit-local-juju-users-3: 12:58:05 ERROR unit.local-juju-users/3.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 491, in <module>
    main(LocalJujuUsersCharm)
  File "/var/lib/juju/agents/unit-local-juju-users-3/charm/venv/ops/main.py", line 436, in main
    framework.reemit()
  File "/var/lib/juju/agents/unit-local-juju-users-3/charm/venv/ops/framework.py", line 866, in reemit
    self._reemit()
  File "/var/lib/juju/agents/unit-local-juju-users-3/charm/venv/ops/framework.py", line 931, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 87, in _on_install
    subprocess.check_call(cmd, universal_newlines=True)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['apt-get', 'install', '-y', 'rsync']' returned non-zero exit status 100.
```
The affected machine had the `rsync` package held:
```
root@infra2:~# dpkg -l | grep "^hi"
hi  rsync                                 3.1.3-8                                         amd64        fast, versatile, remote (and local) file-copying tool
```

**Comment by marcusboden** [comment]
Releasing the hold on that package fixed the issue. But maybe in some other cases, the hold is needed. And I figured that it should still work, if a different version of `rsync` is installed
