### ISSUE TITLE
Crash when credentials.yaml file doesn't exist

### ISSUE THREAD

**Issue by przemeklal** [przemeklal/charm-local-juju-users#4]
On clouds with manual providers credentials.yaml file will not exist. The charm should handle that instead of crashing:
```
unit-local-juju-users-0: 12:32:26 INFO juju.worker.uniter awaiting error resolution for "config-changed" hook
unit-local-juju-users-0: 12:32:26 ERROR unit.local-juju-users/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 450, in <module>
    main(LocalJujuUsersCharm)
  File "/var/lib/juju/agents/unit-local-juju-users-0/charm/venv/ops/main.py", line 438, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-local-juju-users-0/charm/venv/ops/main.py", line 150, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-local-juju-users-0/charm/venv/ops/framework.py", line 355, in emit
    framework._emit(event)  # noqa
  File "/var/lib/juju/agents/unit-local-juju-users-0/charm/venv/ops/framework.py", line 856, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-local-juju-users-0/charm/venv/ops/framework.py", line 931, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 166, in _on_config_changed
    self._update_relation_data()
  File "./src/charm.py", line 251, in _update_relation_data
    credentials = read_credentials_file(self.model.config["juju-admin-unix-account"])
  File "/var/lib/juju/agents/unit-local-juju-users-0/charm/lib/local_juju_users.py", line 210, in read_credentials_file
    return encode_file_to_base64(credentials_file)
  File "/var/lib/juju/agents/unit-local-juju-users-0/charm/lib/local_juju_users.py", line 188, in encode_file_to_base64
    with open(file_path, "rb") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jujumanage/.local/share/juju/credentials.yaml'
```

**Comment by marcusboden** [comment]
This still persists:
```
unit-local-juju-users-0: 11:44:33 ERROR unit.local-juju-users/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 491, in <module>
    main(LocalJujuUsersCharm)
  File "/var/lib/juju/agents/unit-local-juju-users-0/charm/venv/ops/main.py", line 438, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-local-juju-users-0/charm/venv/ops/main.py", line 150, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-local-juju-users-0/charm/venv/ops/framework.py", line 355, in emit
    framework._emit(event)  # noqa
  File "/var/lib/juju/agents/unit-local-juju-users-0/charm/venv/ops/framework.py", line 856, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-local-juju-users-0/charm/venv/ops/framework.py", line 931, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 182, in _on_config_changed
    self._update_relation_data()
  File "./src/charm.py", line 269, in _update_relation_data
    self._set_peer_data("credentials", credentials)
  File "./src/charm.py", line 200, in _set_peer_data
    self.peers.data[self.app][key] = json.dumps(data)
  File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
unit-local-juju-users-0: 11:44:33 ERROR juju.worker.uniter.operation hook "config-changed" (via hook dispatching script: dispatch) failed: exit status 1
```
The dummy contents are not utf-8 encoded. Will open quick PR to fix
